name: researchPython
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - PyTables
  - spacy
  - textblob
  - nltk
  - ipywidgets=7.7.1
  - gensim
  - requests
  - seaborn
  - bokeh
  - lxml
  - cssselect
  - plotnine
  - plotly
  - selenium
  - pip:
    - click
    - requests-html
    - joblib
    - tqdm
    - pqdm
    - scikit-learn 
    - pyldavis
    - fuzzywuzzy
    - jupyterlab-widgets==1.1.1
    - wasabi==0.10.1
    - unidecode